import Head from 'next/head';
import { Roboto } from '@next/font/google';
import { Typography } from 'antd';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen">
          <div className="m-auto">
            <Typography.Title level={2} className={roboto.className}>
              Team Four - CDC
            </Typography.Title>
          </div>
        </div>
      </main>
    </>
  );
}
